# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://levxyca.github.io/
baseurl: /sustain/
title: Leticia Caroline Leonardo
author: Leticia Caroline Leonardo
description: A personal blog made to share my experience in the world of technology.
avatar: profile.png
email: leticialeonardo.contato@gmail.com
github: levxyca # username
twitter: levxyca
instagram: levxyca
linkedin: leticiacaroline
stackoverflow: users/144933/letícia-caroline   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: levxyca
google_analytics: UA-56501008-1


# needed for travis-ci build
exclude: [vendor]
